// Old-origin only. The VPS owns receipt persistence and redemption.
export function migrationConfig(env = process.env) {
  const oldOrigin = exactOrigin(env.DIRECTCHAT_LEGACY_MIGRATION_ORIGIN || "");
  const targetOrigin = exactOrigin(env.DIRECTCHAT_LEGACY_MIGRATION_TARGET || "");
  return oldOrigin && targetOrigin ? { oldOrigin, targetOrigin } : null;
}
function exactOrigin(value) { try { const url = new URL(String(value || "")); return url.protocol === "https:" && !url.username && !url.password && !url.port && url.pathname === "/" && !url.search && !url.hash ? url.origin : ""; } catch { return ""; } }
export function legacyDoorwayHTML(config) {
  const safe = JSON.stringify(config).replaceAll("<", "\\u003c");
  return `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Move DirectChat</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f3f5f9;font:16px system-ui;color:#101828}.card{width:min(440px,calc(100% - 40px));padding:28px;border:1px solid #d9e0eb;border-radius:20px;background:#fff}button{width:100%;padding:13px;border:0;border-radius:12px;background:#0a84ff;color:#fff;font-weight:700;font-size:16px}</style><main class="card"><h1>Move DirectChat securely</h1><p>Your account can move to the new secure service in one step.</p><button id="move">Move my DirectChat</button><p id="status" role="status"></p></main><script>(${doorway.toString()})(${safe})</script>`;
}
async function doorway(config) { const button=document.getElementById("move"), status=document.getElementById("status"), enc=new TextEncoder(); const b64=b=>btoa(String.fromCharCode(...b)).replaceAll("+","-").replaceAll("/","_").replaceAll("=",""); const sha=async v=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",typeof v==="string"?enc.encode(v):v))).map(x=>x.toString(16).padStart(2,"0")).join(""); const random=n=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return b}; const request=r=>new Promise((a,b)=>{r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)}); const done=t=>new Promise((a,b)=>{t.oncomplete=a;t.onerror=()=>b(t.error);t.onabort=()=>b(t.error)}); button.onclick=async()=>{button.disabled=true;status.textContent="Preparing your secure move…";try{const opening=indexedDB.open("directchat-web",2),db=await request(opening),names=["kv","messages","blobs"];if(!names.every(n=>db.objectStoreNames.contains(n))||Array.from(db.objectStoreNames).some(n=>!names.includes(n)))throw Error("This browser has an unsupported DirectChat storage format.");const snapshot={};for(const n of names){const t=db.transaction(n,"readonly"),s=t.objectStore(n),keys=await request(s.getAllKeys()),values=await request(s.getAll());await done(t);snapshot[n]={keys,values:await Promise.all(values.map(async v=>v instanceof Blob?{blob:true,type:v.type,bytes:b64(new Uint8Array(await v.arrayBuffer()))}:v))}}db.close();const state=snapshot.kv.values[snapshot.kv.keys.indexOf("state")];if(!state?.identity?.userID||!state.accounts?.some(a=>a.id===state.identity.userID))throw Error("No transferable DirectChat account was found in this browser.");const plain=enc.encode(JSON.stringify(snapshot)),keyBytes=random(32),nonce=random(12),secret=b64(random(32)),key=await crypto.subtle.importKey("raw",keyBytes,"AES-GCM",false,["encrypt"]),cipher=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:nonce},key,plain));status.textContent="Moving your encrypted account…";const res=await fetch(config.targetOrigin+"/api/legacy-migration/exchanges",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({secretHash:await sha(secret),payload:{nonceBase64:b64(nonce),ciphertextBase64:b64(cipher),sourceDigest:await sha(plain)}})});if(!res.ok)throw Error("The secure service could not accept this move. Please try again.");const receipt=await res.json();location.replace(receipt.target+"#receipt="+encodeURIComponent(receipt.token+"."+secret)+"."+b64(keyBytes))}catch(e){button.disabled=false;status.textContent=e instanceof Error?e.message:"The move could not be completed. Please try again."}} }
